// Generated by FlutterFire CLI.
// Run:
//   flutterfire configure
//
// This placeholder exists so the repo compiles after you generate the real file.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'Missing firebase_options.dart. Run `flutterfire configure` inside finence_mobile/.',
    );
  }
}


